// Offer Actions types

export enum offersTypes {
    FETCH_OFFERS_REQUEST = "FETCH_OFFERS_REQUEST",
    FETCH_OFFERS_DATA_SUCCESS = "FETCH_OFFERS_DATA_SUCCESS",
    FETCH_OFFERS_DATA_ERROR = "FETCH_OFFERS_DATA_ERROR"
}